e_commerce/admin_dashboard/urls.py
from django.urls import path

from . import views

app_name = 'admin_dashboard'
urlpatterns = [
    path('', views.home, name='home')
]

e_commerce/authentication/urls.py
from django.urls import path

from . import views

app_name = 'authentication'
urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register, name='register'),
    path('welcome/', views.welcome, name='welcome'),
]

e_commerce/e_commerce/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'e_commerce'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_dahsboard/', include('admin_dashboard.urls')),
    path('auth/', include('authentication.urls')),
    path('shop/', include('shop.urls')),
]

e_commerce/shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.home, name='home'),
]

e_commerce/admin_dashboard/models.py
from django.db import models

# Create your models here.

e_commerce/authentication/models.py
from django.db import models

# Create your models here.

e_commerce/shop/models.py
from django.db import models

# Create your models here.

e_commerce/admin_dashboard/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'admin_dashboard/home.html', {})

e_commerce/authentication/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages


# register new users
# /auth/register/ :POST
def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        password1 = request.POST["password"]
        password2 = request.POST["confirm_password"]

        if username and email and password1 and password2:
            # check if passwords match each other
            if password1 != password2:
                messages.error(request, "password dosn't match!")

            try:
                user = User.objects.create_user(
                    username=username, email=email, password=password1
                )

            except:
                messages.error(request, "try defferant username or email!")

            if user is not None:
                login(request, user)
                return redirect("/auth/welcome/")

    return render(request, "authentication/register.html", {})


# login user to access the system
# /auth/login/ :POST
def login_user(request):
    if request.user.is_authenticated:
        return redirect("/shop/")

    if request.method == "POST":
        username = request.POST["username"].lower()
        password = request.POST["password"]

        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, "User does not exits")

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect("/shop/")
        else:
            messages.error(request, "Usernaem or password does not correct")

    return render(request, "authentication/login.html", {})


# logout user
# /auth/logout/ :POST
def logout_user(request):
    logout(request)

    return redirect("/shop/")


# welcome page
# /auth/welcome/ :GET
def welcome(request):
    return render(request, "authentication/welcome.html", {})

e_commerce/shop/views.py
from django.shortcuts import render


def home(request):
    return render(request, "shop/home.html", {})

e_commerce/admin_dashboard/templates/admin_dashboard/home.html
{% extends "main.html" %}

{% block content %}
    <h1>Admin home</h1>
{% endblock content %}

e_commerce/authentication/templates/authentication/login.html
{% extends "main.html" %}

{% block content %}
<div class="contact">
    <h2 class="heading">Login</h2>
    <form class="checkout-form" method="post">
        {% csrf_token %} 
        <div class="form-group">
            <label>Username</label>
            <input autofocus required type="text" id="username" name="username">
        </div>
        <div class="form-group">
            <label>Password</label>
            <input required type="password" id="password" name="password">
        </div>
        <div class="form-group">
            <label></label>
            <input type="submit" id="login" name="login" value="Login">
        </div>
    </form>	
</div>
{% endblock content %}

e_commerce/authentication/templates/authentication/register.html
{% extends "main.html" %}

{% block content %}
<div class="contact">
    <h2 class="heading">Register</h2>
    <form class="checkout-form" method="post">
        {% csrf_token %} 
        <div class="form-group">
            <label>Username</label>
            <input autofocus required type="text" id="username" name="username">
        </div> 
        <div class="form-group">
            <label>Email</label>
            <input required type="email" id="email" name="email">
        </div>
        <div class="form-group">
            <label>Password</label>
            <input required type="password" id="password" name="password">
        </div>
        <div class="form-group">
            <label>Confirm password</label>
            <input required type="password" id="pconfirm_passwordassword" name="confirm_password">
        </div>
        <div class="form-group">
            <label></label>
            <input type="submit" id="register" name="register" value="Register">
        </div>
    </form>	
</div>
{% endblock content %}

e_commerce/authentication/templates/authentication/welcome.html
{% extends "main.html" %}

{% block content %}
<div class="contact">
    <h2 class="heading">Welcome {{request.user}}</h2>
    <div class='mystyle'><a class='headding' href="{% url 'shop:home' %}">Go to Home</a></div>
</div>
{% endblock content %}

e_commerce/shop/templates/shop/home.html
{% extends "main.html" %}
{% load static %}

{% block content %}
<div class="slider">
    <div class="slide-1">
      <img src="{% static 'img/slider/slide-1.jpg' %}" />
      <div class="slider-text">
        <h3>Sale 40% off</h3>
        <h2>Men's Watches</h2>
        <a href="#">Shop Now</a>
      </div>
    </div>
    <div class="slide-2">
      <img src="{% static 'img/slider/slide-2.jpg' %}" />
      <div class="slider-text">
        <h3>Sale 20% off</h3>
        <h2>Women's Fashion</h2>
        <a href="#">Shop Now</a>
      </div>
    </div>
    <div class="slide-3">
      <img src="{% static 'img/slider/slide-3.jpg' %}" />
      <div class="slider-text">
        <h3>Sale 50% off</h3>
        <h2>Women's Collection</h2>
        <a href="#">Shop Now</a>
      </div>
    </div>
  </div>
  <!-- slider -->

  <div class="new-product-section">
    <div class="product-section-heading">
      <h2>Tranding Products <img src="{% static 'img/icons/increase.png' %}" /></h2>
      <h3>Most selling product for the month</h3>
    </div>
    <div class="product-content">
      <div class="product">
        <a href="product.html">
          <img src="{% static 'img/product/img1.jpg' %}" />
        </a>
        <div class="product-detail">
          <h3>Men's / Watches</h3>
          <h2>Gray Color Men's Watch</h2>
          <a href="#">Add to Cart</a>
          <p>Rs.4500/-</p>
        </div>
      </div>
      <div class="product">
        <a href="product.html">
          <img src="{% static 'img/product/img2.jpg' %}" />
        </a>
        <div class="product-detail">
          <h3>Men's / Pants</h3>
          <h2>Levi's Jeans Pant</h2>
          <a href="#">Add to Cart</a>
          <p>Rs.2000/-</p>
        </div>
      </div>
      <div class="product">
        <a href="product.html">
          <img src="{% static 'img/product/img3.jpg' %}" />
        </a>
        <div class="product-detail">
          <h3>Men's / Watches</h3>
          <h2>Black Men's Watch</h2>
          <a href="#">Add to Cart</a>
          <p>Rs.4000/-</p>
        </div>
      </div>
      <div class="product">
        <a href="product.html">
          <img src="{% static 'img/product/img4.jpg' %}" />
        </a>
        <div class="product-detail">
          <h3>Men's / Shoes</h3>
          <h2>Nick Black Sneakers</h2>
          <a href="#">Add to Cart</a>
          <p>Rs.3200/-</p>
        </div>
      </div>
      <div class="product">
        <a href="product.html">
          <img src="{% static 'img/product/img5.jpg' %}" />
        </a>
        <div class="product-detail">
          <h3>Glasses</h3>
          <h2>Wood Frame Sun Glass</h2>
          <a href="#">Add to Cart</a>
          <p>Rs.1200/-</p>
        </div>
      </div>
      <div class="product">
        <a href="product.html">
          <img src="{% static 'img/product/img6.jpg' %}" />
        </a>
        <div class="product-detail">
          <h3>Women's / Hand Bags</h3>
          <h2>Leather Hand Bag</h2>
          <a href="#">Add to Cart</a>
          <p>Rs.3800/-</p>
        </div>
      </div>
      <div class="product">
        <a href="product.html">
          <img src="{% static 'img/product/img7.jpg' %}" />
        </a>
        <div class="product-detail">
          <h3>Men's / Shoes</h3>
          <h2>Men's Sneaker</h2>
          <a href="#">Add to Cart</a>
          <p>Rs.3500/-</p>
        </div>
      </div>
      <div class="product">
        <a href="product.html">
          <img src="{% static 'img/product/img8.jpg' %}" />
        </a>
        <div class="product-detail">
          <h3>Women's / Hand Bags</h3>
          <h2>Brown Leather Hand Bag</h2>
          <a href="#">Add to Cart</a>
          <p>Rs.5200/-</p>
        </div>
      </div>
    </div>
  </div>
  <!-- New Product Section -->

  <div class="collection">
    <div class="men-collection">
      <h2>Men's Collection</h2>
    </div>
    <div class="women-collection">
      <h2>Women's Collection</h2>
    </div>
  </div>
  <!-- Collection Section -->

  <div class="new-product-section">
    <div class="product-section-heading">
      <h2>Recommend Products <img src="{% static 'img/icons/good_quality.png' %}" /></h2>
      <h3>OUR BEST PRODUCTS RECOMMENDED FOR YOU</h3>
    </div>
    <div class="product-content">
      <div class="product">
        <a href="product.html">
          <img src="{% static 'img/product/img1.jpg' %}" />
        </a>
        <div class="product-detail">
          <h3>Men's / Watches</h3>
          <h2>Gray Color Men's Watch</h2>
          <a href="#">Add to Cart</a>
          <p>Rs.4500/-</p>
        </div>
      </div>
      <div class="product">
        <a href="product.html">
          <img src="{% static 'img/product/img2.jpg' %}" />
        </a>
        <div class="product-detail">
          <h3>Men's / Pants</h3>
          <h2>Levi's Jeans Pant</h2>
          <a href="#">Add to Cart</a>
          <p>Rs.2000/-</p>
        </div>
      </div>
      <div class="product">
        <a href="product.html">
          <img src="{% static 'img/product/img3.jpg' %}" />
        </a>
        <div class="product-detail">
          <h3>Men's / Watches</h3>
          <h2>Black Men's Watch</h2>
          <a href="#">Add to Cart</a>
          <p>Rs.4000/-</p>
        </div>
      </div>
      <div class="product">
        <a href="product.html">
          <img src="{% static 'img/product/img4.jpg' %}" />
        </a>
        <div class="product-detail">
          <h3>Men's / Shoes</h3>
          <h2>Nick Black Sneakers</h2>
          <a href="#">Add to Cart</a>
          <p>Rs.3200/-</p>
        </div>
      </div>
    </div>
  </div>
  <!-- Recommend Product Section -->
{% endblock content %}

e_commerce/templates/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Meta Tags -->
    <meta charset="UTF-8" />
    <meta name="author" content="Kamran Mubarik" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Title -->
    <title>E-Commerce Online Shop</title>
    <!-- Style Sheet -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/my_style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <!-- Javascript -->
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css"
    />
    <script src="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"></script>
    <script>
      $(document).ready(function () {
        $(".slider").bxSlider({
          auto: true,
          autoControls: true,
          stopAutoOnClick: true,
          pager: true,
        });
      });
    </script>
  </head>
  <body>
    <header>
      <div class="container">
        <div class="brand">
          <div class="logo">
            <a href="index.html">
              <img src="{% static 'img/icons/online_shopping.png' %}" />
              <div class="logo-text">
                <p class="big-logo">Ecommerce</p>
                <p class="small-logo">online shop</p>
              </div>
            </a>
          </div>
          {% if user.is_authenticated %}
          <!-- logo -->
          <div class="shop-icon">
            <div class='dropdown'>{{request.user}}</div>
            <div class="dropdown">
              <img src="{% static 'img/icons/account.png' %}" />
              <div class="dropdown-menu">
                <ul>
                  <li><a href="account.html">My Account</a></li>
                  <li><a href="orders.html">My Orders</a></li>
                </ul>
              </div>
            </div>
            <div class="dropdown">
              <img src="{% static 'img/icons/heart.png' %}" />
              <div class="dropdown-menu wishlist-item">
                <table border="1">
                  <thead>
                    <tr>
                      <th>Image</th>
                      <th>Product Name</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td><img src="{% static 'img/product/img1.jpg' %}" /></td>
                      <td>product name</td>
                    </tr>
                    <tr>
                      <td><img src="{% static 'img/product/img2.jpg' %}" /></td>
                      <td>product name</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
            <div class="dropdown">
              <img src="{% static 'img/icons/shopping_cart.png' %}" />
              <div class="dropdown-menu cart-item">
                <table border="1">
                  <thead>
                    <tr>
                      <th>Image</th>
                      <th>Product Name</th>
                      <th class="center">Price</th>
                      <th class="center">Qty.</th>
                      <th class="center">Amount</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td><img src="{% static 'img/product/img1.jpg' %}" /></td>
                      <td>product name</td>
                      <td class="center">1200</td>
                      <td class="center">2</td>
                      <td class="center">2400</td>
                    </tr>
                    <tr>
                      <td><img src="{% static 'img/product/img2.jpg' %}" /></td>
                      <td>product name</td>
                      <td class="center">1500</td>
                      <td class="center">2</td>
                      <td class="center">3000</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
            <div class='menu'>
              <ul>
                <li><a href="{% url 'authentication:logout' %}">Logout</a></li>
              </ul>
            </div>
          </div>
          <!-- shop icons -->
          {% else %}
            <div class="menu-bar">
              <div class="menu">
                <ul>
                  <li><a href="{% url 'authentication:login' %}">Login</a></li>
                  <li><a href="{% url 'authentication:register' %}">Register</a></li>
                </ul>
              </div>
            </div>
          {% endif %}
        </div>
        <!-- brand -->

        <div class="menu-bar">
          <div class="menu">
            <ul>
              <li><a href="{% url 'shop:home' %}">Home</a></li>
              <li><a href="shop.html">Shop</a></li>
              <li><a href="about.html">About</a></li>
              <li><a href="contact.html">Contact</a></li>
            </ul>
          </div>
          <div class="search-bar">
            <form>
              <div class="form-group">
                <input
                  type="text"
                  class="form-control"
                  name="search"
                  placeholder="Search"
                />
                <img src="{% static 'img/icons/search.png' %}" />
              </div>
            </form>
          </div>
        </div>
        <!-- menu -->
      </div>
      <!-- container -->
    </header>
    <!-- header -->

    <div class="container">
      <main>
        {% if messages %}
        {% for message in messages %}
          <div class='error'>Error::{{message}}</div>
        {% endfor %}
        {% endif %}
        {% block content %}
        {% endblock content %}
      </main>
      <!-- Main Area -->
    </div>

    <footer>
      <div class="container">
        <div class="footer-widget">
          <div class="widget">
            <div class="widget-heading">
              <h3>Important Link</h3>
            </div>
            <div class="widget-content">
              <ul>
                <li><a href="about.html">About</a></li>
                <li><a href="contact.html">Contact</a></li>
                <li><a href="refund.html">Refund Policy</a></li>
                <li><a href="terms.html">Terms & Conditions</a></li>
              </ul>
            </div>
          </div>
          <div class="widget">
            <div class="widget-heading">
              <h3>Information</h3>
            </div>
            <div class="widget-content">
              <ul>
                <li><a href="account.html">My Account</a></li>
                <li><a href="orders.html">My Orders</a></li>
                <li><a href="cart.html">Cart</a></li>
                <li><a href="checkout.html">Checkout</a></li>
              </ul>
            </div>
          </div>
          <div class="widget">
            <div class="widget-heading">
              <h3>Follow us</h3>
            </div>
            <div class="widget-content">
              <div class="follow">
                <ul>
                  <li>
                    <a href="#"><img src="{% static 'img/icons/facebook.png' %}" /></a>
                  </li>
                  <li>
                    <a href="#"><img src="{% static 'img/icons/twitter.png' %}" /></a>
                  </li>
                  <li>
                    <a href="#"><img src="{% static 'img/icons/instagram.png' %}" /></a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="widget-heading">
              <h3>Subscribe for Newsletter</h3>
            </div>
            <div class="widget-content">
              <div class="subscribe">
                <form>
                  <div class="form-group">
                    <input
                      type="text"
                      class="form-control"
                      name="subscribe"
                      placeholder="Email"
                    />
                    <img src="{% static 'img/icons/paper_plane.png' %}" />
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
        <!-- Footer Widget -->
        <div class="footer-bar">
          <div class="copyright-text">
            <p>Copyright 2021 - All Rights Reserved</p>
          </div>
          <div class="payment-mode">
            <img src="{% static 'img/icons/paper_money.png' %}" />
            <img src="{% static 'img/icons/visa.png' %}" />
            <img src="{% static 'img/icons/mastercard.png' %}" />
          </div>
        </div>
        <!-- Footer Bar -->
      </div>
    </footer>
    <!-- Footer Area -->
  </body>
</html>